import 'dart:async';
import 'dart:ffi';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';
import 'package:bigexpress_driver/pages/topup_page/topup_list_payment_page.dart';
import 'package:flutter_background/flutter_background.dart';
import 'package:maps_toolkit/maps_toolkit.dart' as mapTool;
import 'package:currency_text_input_formatter/currency_text_input_formatter.dart';
import 'package:flutter/gestures.dart';
import 'package:webview_flutter/webview_flutter.dart' as wv;
import 'package:bigexpress_driver/services/services.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_easyloading/flutter_easyloading.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:just_audio/just_audio.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:string_validator/string_validator.dart';
import 'package:flutter_multi_formatter/flutter_multi_formatter.dart';
import 'package:bigexpress_driver/cubits/cubits.dart';
import 'package:bigexpress_driver/models/models.dart';
import 'package:bigexpress_driver/shared/shared.dart';
import 'package:bigexpress_driver/widgets/widgets.dart';
import 'package:dotted_border/dotted_border.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_polyline_points/flutter_polyline_points.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:percent_indicator/percent_indicator.dart';
import 'package:pinput/pinput.dart';
import 'package:sizer/sizer.dart';
import 'package:url_launcher/url_launcher.dart';
part 'splash_screen_page.dart';
part 'auth/login_page.dart';
part 'auth/register_page.dart';
part 'auth/otp_page.dart';

part 'dashboard/main_page.dart';
part 'dashboard/available_order_section.dart';
part 'dashboard/active_order_section.dart';
part 'dashboard/done_order_section.dart';

part 'dashboard/profile_page/profile_page.dart';
part 'dashboard/profile_page/statistic_page.dart';
part 'dashboard/profile_page/profile_form_page.dart';
part 'dashboard/profile_page/vehicle_form_page.dart';

part 'dashboard/withdraw/withdraw_page.dart';
part 'dashboard/withdraw/account_bank_form_page.dart';
part 'dashboard/withdraw/withdraw_list_page.dart';

part 'detail_order_page.dart';
part 'done_order_page.dart';
part 'dashboard/general_order_section.dart';
part 'dashboard/special_order_section.dart';

part 'topup_page/topup_confirmation_page.dart';
part 'topup_page/topup_list_page.dart';
part 'topup_page/topup_page.dart';
part 'topup_page/topup_select_payment_page.dart';
part 'location_request_page.dart';
part 'topup_page/topup_webview.dart';
part 'topup_page/finish_payment_page.dart';

part 'app_locked_page.dart';
part 'failed_check_location_page.dart';
